config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("gunio.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

gunio/users/urls.py
from django.urls import path

from gunio.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
    delete_view,
    FriendshipCreateView,
    ApproveFreindshipView,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
    path('delete-entry/<pk>/', view=delete_view, name='delete_view'),
    path('add_view/<friend_id>/', view=FriendshipCreateView, name='add_view'),
    path('approve_view/<int:id>/', view=ApproveFreindshipView, name='approve_view'),
]

gunio/common/models.py
from django.db import models

# Create your models here.

gunio/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _

from gunio.common.mixins import TimeStampMixin
from django.http.response import JsonResponse

from django.db.models import Q


STATUS_CHOICES = [
    ('pending', 'Pending'),
    ('accepted', 'Accepted'),
    ('declined', 'Declined')
]


class User(AbstractUser):

    name = models.CharField(_("Name of User"), blank=True, max_length=255)
    profile_image = models.ImageField(upload_to='uploads/', null=True, blank=False, default="uploads/not-found.png")
    address = models.CharField(_("Address"), blank=True, null=False, max_length=255)
    address_cont = models.CharField(_(""), blank=True, null=False, max_length=255)
    address_city = models.CharField(_("City"), blank=True, null=True, max_length=255)
    address_state = models.CharField(_("State"), blank=True, null=False, max_length=255)
    address_zipcode = models.CharField(_("Zipcode"), blank=True, null=False, max_length=255)

    def get_friends(self):
        friends = Friendship.objects.filter(Q(creator=self.id) | Q(friend_id=self.id)).exclude(status="declined").all()
        return friends

    def get_all_users(self):
        all_users = User.objects.all()
        return all_users

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})


class Friendship(models.Model):
    # TODO: Create a datetime field for friends since invite accepted.
    created = models.DateTimeField(auto_now_add=True, editable=False)
    approved = models.DateTimeField(null=True)
    creator = models.ForeignKey(User, related_name="friendship_creator_set", on_delete=models.CASCADE)
    friend = models.ForeignKey(User, related_name="friend_set", on_delete=models.CASCADE)
    status = models.CharField(
        max_length=8,
        choices=STATUS_CHOICES,
        default="pending"
    )

gunio/users/forms.py
from django.contrib.auth import forms, get_user_model
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

gunio/common/views.py
from django.shortcuts import render

# Create your views here.

gunio/users/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView, DeleteView, CreateView
from .models import Friendship
from django.http import HttpResponseRedirect
from django.contrib.messages.views import SuccessMessageMixin
from django.views import View
from datetime import datetime

User = get_user_model()


def FriendshipCreateView(request, friend_id):
    friendship = Friendship(creator_id=request.user.id, friend_id=friend_id, status="pending")
    friendship.save()

    return HttpResponseRedirect('/users/'+request.user.username)


def ApproveFreindshipView(request, id):
    friendship = Friendship.objects.get(id=id)
    friendship.status = "approved"
    friendship.approved = datetime.now()
    friendship.save()

    return HttpResponseRedirect('/users/'+request.user.username)


class DeleteView(SuccessMessageMixin, DeleteView):
    model = Friendship
    success_url = '/users/~redirect/'
    success_message = "deleted..."

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super(DeleteView, self).delete(request, *args, **kwargs)


delete_view = DeleteView.as_view()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["first_name", "last_name", "email", "profile_image"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)

    def form_valid(self, form):
        messages.add_message(
            self.request, messages.INFO, _("Infos successfully updated")
        )
        return super().form_valid(form)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

gunio/templates/base.html
{% load static i18n %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block title %}GunIO{% endblock title %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

  <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">

  {% block css %}

  <!-- Latest compiled and minified Bootstrap CSS -->
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


  <!-- Your stuff: Third-party CSS libraries go here -->

  <!-- This file stores project-specific CSS -->

  <link href="{% static 'css/project.css' %}" rel="stylesheet">


  {% endblock %}

</head>

<body>

  <div class="mb-1">
    <nav class="navbar navbar-expand-md navbar-light bg-light">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
        data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
        aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="{% url 'home' %}">GunIO</a>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            {# URL provided by django-allauth/account/urls.py #}
            <a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
          </li>
          <li class="nav-item">
            {# URL provided by django-allauth/account/urls.py #}
            <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
          </li>
          {% else %}
          <li class="nav-item">
            {# URL provided by django-allauth/account/urls.py #}
            <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
          </li>
          <li class="nav-item">
            {# URL provided by django-allauth/account/urls.py #}
            <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>

  </div>

  <div class="container-fluid">

    {% if messages %}
    {% for message in messages %}
    <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}<button type="button"
        class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>
    {% endfor %}
    {% endif %}

    {% block content %}
    <p>Welcome to my quick social network demo. You may currently log in with user1/user2/user3 with the password 'password' without quotes. You'll find in the profile section, two lists. One is your current and
      pending friends and the other is a list of all users to choose from. You can see your user/email information in the respective sections in the top right corner once you've logged in.</p>
    <p>This demo was started from a cookie cutter created by <a href="https://github.com/pydanny/cookiecutter-django">PyDanny</a>. I have created a very straight forward barebones prototype of a social network. Registration and Login currently print any confirmation links to console <b>ONLY</b>. User must confirm email address before logging in.</p>
    <p>Completely capable TODO's:
      <ul>
        <li>Leverage ModelManger/QuerySetManager to maintain relational functions (add/delete/approve)</li>
        <li>Implment Celery/RabbitMQ to manage notifications of requests/messages.</li>
        <li>Add Vue frontend and leverage Djangos restframework to serve all requests.</li>
      </ul>
    </p>
    {% endblock content %}

  </div> <!-- /container -->

  {% block modal %}{% endblock modal %}

  <!-- Le javascript
    ================================================== -->
  <!-- Placed at the end of the document so the pages load faster -->
  {% block javascript %}

  <!-- Bootstrap JS and its dependencies-->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
    integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>

  <!-- Your stuff: Third-party javascript libraries go here -->


  <!-- place project specific Javascript in this file -->

  <script src="{% static 'js/project.js' %}"></script>


  {% endblock javascript %}
</body>

</html>

gunio/templates/pages/about.html
{% extends "base.html" %}

gunio/templates/pages/home.html
{% extends "base.html" %}

gunio/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}

{% if object == request.user %}


<div class="row">
  <div class="col">
    <h2><img src="/media/{{ user.profile_image }}" width="42" height="42" class="rounded-circle" />
      {{ user.username }}</h2>
  </div>
  <div class="col" style="text-align: right; margin-top: 5px">
    <!-- Action buttons -->
    <a class="btn btn-primary" href="{% url 'users:update' %}" role="button">My Info</a>
    <a class="btn btn-primary" href="{% url 'account_email' %}" role="button">E-Mail</a>
    <!-- End Action buttons -->
  </div>
</div>
<div class="container">
<div class="row">
  <div class="col">
    <p>Welcome to my quick social network demo. You'll find in the profile section, two lists. One is your current and
      pending friends and the other is a list of all users to choose from. You can see your user/email information in the respective sections in the top right corner once you've logged in.</p>
      
    <p>This demo was begun from a cookie cutter created by <a href="https://github.com/pydanny/cookiecutter-django">PyDanny</a>. I have created a very straight forward barebones prototype. Registration and Login currently print any confirmation links to console <b>ONLY</b>.</p>
  </div>
</div>
</div>
<div class="row">
  <div class="col">
    <h4>My Friends</h4>
    <table class="table">
      <tr>
        <td></td>
        <td>UserName</td>
        <td>Name</td>
        <td>Friends Since</td>
        <td>Actions</td>
      </tr>
      {% for friend in object.get_friends %}

      {% if object.username == friend.creator.username %}
      <tr>
        <td><img src="/media/{{ friend.friend.profile_image }}" width="42" height="42" class="rounded-circle" /></td>
        <td>{{ friend.friend.username }}</td>
        <td>{{ friend.friend.first_name }} {{ friend.friend.last_name }}</td>
        <td>{{ friend.approved|timesince }}</td>
        <td>

          {% if friend.status != "declined" %}
            <form action="{% url 'users:delete_view' pk=friend.pk %}" method="POST" style="display: inline;">
              {% csrf_token %}
              <input class="btn btn-default btn-danger" type="submit" value="X" />
            </form>
          {% endif %}

          {% if friend.status == "pending" %}
            {% if object.username == friend.creator.username %}
              <button class="btn btn-secondary btn-sm">Pending</button>
            {% else %}
              <form action="{% url 'users:approve_view' friend.id %}" method="POST" style="display: inline;">
                {% csrf_token %}
                <input class="btn btn-default btn-success" type="submit" value="√" />
              </form>
            {% endif %}
          {% endif %}

        </td>
      </tr>
      {% else %}
      <tr>
        <td><img src="/media/{{ friend.creator.profile_image }}" width="42" height="42" class="rounded-circle" /></td>
        <td>{{ friend.creator.username }}</td>
        <td>{{ friend.creator.first_name }} {{ friend.creator.last_name }}</td>
        <td>{{ friend.approved|timesince }}</td>
        <td>

          {% if friend.status != "declined" %}
            <form action="{% url 'users:delete_view' pk=friend.pk %}" method="POST" style="display: inline;">
              {% csrf_token %}
              <input class="btn btn-default btn-danger" type="submit" value="X" />
            </form>
          {% endif %}

          {% if friend.status == "pending" %}
            {% if object.username == friend.creator.username %}
              <button class="btn btn-secondary btn-sm">Pending</button>
            {% else %}
              <form action="{% url 'users:approve_view' friend.id %}" method="POST" style="display: inline;">
                {% csrf_token %}
                <input class="btn btn-default btn-success" type="submit" value="√" />
              </form>
            {% endif %}
          {% endif %}

        </td>
      </tr>
      {% endif %}

      {% endfor %}

    </table>
  </div>
  <div class="col">
    <h4>All Users</h4>
    <table class="table">
      <tr>
        <td></td>
        <td>UserName</td>
        <td>Name</td>
        <td>Actions</td>
      </tr>
      {% for user in object.get_all_users %}
      <tr>
        <td><img src="/media/{{ user.profile_image }}" width="42" height="42" class="rounded-circle" /></td>
        <td>{{ user.username }} {% if user.username == object.username %}<small>(ME)</small>{% endif %}</td>
        <td>{{ user.first_name }} {{ user.last_name }}</td>
        <td>
          {% if user.username != object.username %}
          <form action="{% url 'users:add_view' user.id %}" method="POST">
            {% csrf_token %}
            <input class="btn btn-default btn-success" type="submit" value="+" />
          </form>
          {% endif %}
        </td>
      </tr>
      {% endfor %}

    </table>
  </div>
</div>


{% endif %}

{% endblock content %}

gunio/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}

<div class="container">
  <div class="row">
    <div class="col">
      <h2><img src="/media/{{ user.profile_image }}" width="42" height="42" class="rounded-circle" />
        {{ user.username }}</h2>
      <hr />
      <form class="form-horizontal" method="post" enctype="multipart/form-data" action="{% url 'users:update' %}">
        {% csrf_token %}
        {{ form|crispy }}
        <div class="control-group">
          <hr />
          <div class="controls">
            <a class="btn btn-secondary" href="javascript:history.back()">Cancle</a></button>
            <button type="submit" class="btn btn-primary">Update</button>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}